# NUMPY ARRAY

In [1]:
import numpy as np

In [2]:
np.array(["vbhvh", 2, 3])

array(['vbhvh', '2', '3'], dtype='<U5')

In [3]:
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [4]:
#Upcasting:convert,typecast or upcast All the integers into float 

In [5]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [6]:
np.array([1,4.0,5,9])

array([1., 4., 5., 9.])

In [7]:
np.array([1.0,4,5,9.0])

array([1., 4., 5., 9.])

In [8]:
#two dimensions ----->>>>  List of list hoga 

np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [9]:
#Minimum dimensions 2:

np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [10]:
## 6 opening and 6 closing brackets
np.array([1, 2, 3, 4], ndmin=6)

array([[[[[[1, 2, 3, 4]]]]]])

In [11]:
#dtype or datatype() in this data type you can change but value will remain same only type of data will change

np.array([1, 2, 3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
np.array([3, 4, 5], dtype = list)

array([3, 4, 5], dtype=object)

In [13]:
np.array([3, 4, 5, 6, 7], dtype = list)

array([3, 4, 5, 6, 7], dtype=object)

In [14]:
np.array([3, 4, 5, 6, 7], dtype = object)

array([3, 4, 5, 6, 7], dtype=object)

In [15]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [16]:
n = np.array([(1,2),(3,4)])

In [17]:
n[0]

array([1, 2])

In [18]:
n[1]

array([3, 4])

In [19]:
n[0][1]

2

In [20]:
n[1][1]

4

In [21]:
type(n[1][1])

numpy.int32

In [22]:
type(n[0])

numpy.ndarray

In [23]:
type(n[0][1])

numpy.int32

In [24]:
type(n)

numpy.ndarray

In [25]:
#Data-type consisting of more than one element:

x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [26]:
type(x[1][0])

numpy.int16

In [27]:
#Creating an array from sub-classes: sub classses like --->>> MATRICES and it is sub class of arrayalso:

np.array([(1,3),(5,7)])

array([[1, 3],
       [5, 7]])

In [28]:
### 2nd method of array representation
np.array([[1,3],[5,7]])

array([[1, 3],
       [5, 7]])

In [29]:
np.mat(np.array([[1,3],[5,7]]))

matrix([[1, 3],
        [5, 7]])

In [30]:
type(np.mat(np.array([[1,3],[5,7]])))

numpy.matrix

In [31]:
## 2nd method of converting into matrices

np.mat("1 2;3 4")

matrix([[1, 2],
        [3, 4]])

In [32]:
np.mat([1,2])

matrix([[1, 2]])

In [33]:
### List of List
np.mat([[1,2],[3,5]])

matrix([[1, 2],
        [3, 5]])

In [40]:
np.mat([[1,2],[3,5,7]])

C:\Users\goodluck\anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr = N.array(data, dtype=dtype, copy=copy)


matrix([[list([1, 2]), list([3, 5, 7])]], dtype=object)

## numpy.asarray

In [ ]:
#Convert the input to an array.

In [ ]:
#Convert a list into an array:

In [41]:
 a = [1, 2]
type(a)

list

In [42]:
v = (1,2,3)
type(v)

tuple

In [43]:
type(np.asarray(a))

numpy.ndarray

In [44]:
a = np.array([3, 5]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [45]:
np.asarray((1,2))

array([1, 2])

In [46]:
np.asarray([1,3])

array([1, 3])

In [47]:
#If dtype is set, array is copied only if dtype does not match:

In [48]:
a = np.array([1, 2], dtype=float)
a

array([1., 2.])

In [49]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [50]:
np.asarray([1,2]) is a

False

In [51]:
np.asarray([1,2])

array([1, 2])

In [52]:
np.asarray(a, dtype=np.float64) is a

False

In [53]:
# ndarray subclasses are not passed through

In [54]:
### np.matrix is subclass of array = True

issubclass(np.matrix, np.ndarray)

True

In [55]:
### np.ndarray is not subclass of np.matrix  = False

issubclass(np.ndarray,np.matrix)

False

In [56]:
a = np.matrix([[1, 2]])
np.asanyarray(a)

matrix([[1, 2]])

In [57]:
np.asarray(a) is a

False

## numpy.asanyarray

In [58]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [59]:
type(np.asanyarray(a))

numpy.ndarray

In [60]:
b = (1,2)
np.asanyarray(b)

array([1, 2])

In [61]:
type(np.asanyarray(b))

numpy.ndarray

In [62]:
## it is not converting my data in array it is in same matrix format format this is difference between array asarray() and asanyarray()
##it is already in form of matrix and matrix is variance of array

a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [63]:
np.array(a)

array([[1, 2]])

In [64]:
type(np.array(a))

numpy.ndarray

In [65]:
np.asarray(a)

array([[1, 2]])

In [66]:
type(np.asarray(a))

numpy.ndarray

In [67]:
## it is not converting because it is already in ther form of matrix or subclass of array

np.asanyarray(a)

matrix([[1, 2]])

In [68]:
type(np.asanyarray(a))

numpy.matrix

In [69]:
np.asanyarray([1,2]) is a

False

In [70]:
## Deep copy and solo copy

np.array(a, copy=True)  

array([[1, 2]])

In [71]:
#Create an array x, with a reference y and a copy z:

In [72]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [73]:
## it will reference or locate in same space or location in backend values will keep same if anything gonna be change from both of anyone

y = x

In [74]:
y

array([1, 2, 3])

In [75]:
y[1]

2

In [76]:
y[1] = 675

In [77]:
y

array([  1, 675,   3])

In [78]:
#### kuch bhi change hoga dono me se kisi me bhi toh donome same change aayega aur same display karega

x

array([  1, 675,   3])

In [79]:
x[0]

1

In [80]:
x[0] = 778

In [81]:
x

array([778, 675,   3])

In [82]:
y

array([778, 675,   3])

In [83]:
z = np.copy(x)

In [84]:
z

array([778, 675,   3])

In [85]:
z[0]

778

In [86]:
z[0] = 68

In [87]:
z

array([ 68, 675,   3])

In [88]:
## x is not showing the updated situation
## x is showing at different location and z is showing at different location
## both x and z is independent of each other
## this is effect of deep copy 

x

array([778, 675,   3])

## numpy.fromfunction

In [89]:
#Construct an array by executing a function over each coordinate.

In [90]:
import numpy as np

In [91]:
np.fromfunction(lambda i, j: i ==j,(3,3), dtype = int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [92]:
##2-D array

np.fromfunction(lambda i,j : i*j, (3,3), dtype = int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [93]:
##3-D array

np.fromfunction(lambda i,j, k  : i*j*k, (3,3,3), dtype = int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [94]:
##4-D array

np.fromfunction(lambda i,j,k,l  : i*j*k*l,(3,3,3,3), dtype = int)

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]]])

In [95]:
np.fromfunction(lambda i,j,k,l  : i*j*k*l,(2,3,3,3), dtype = int)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 1, 2],
         [0, 2, 4]],

        [[0, 0, 0],
         [0, 2, 4],
         [0, 4, 8]]]])

In [96]:
#Create a new 1-dimensional array from an iterable object.

## this is not useful for generic purpose sudhanshu sir said  //// sudhanshu sir also said he never used..

In [97]:
iterable = (x*x for x in range (5))
iterable

<generator object <genexpr> at 0x0000000005645DD0>

In [98]:
iterable = [x*x for x in range (5)]
iterable

[0, 1, 4, 9, 16]

In [99]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [100]:
#A new 1-D array initialized from text data in a string

In [101]:
a = np.fromstring('234 234', sep = ' ')
a

array([234., 234.])

In [102]:
b = np.fromstring('1 2', sep = ' ')

In [103]:
b

array([1., 2.])

In [104]:
# How to create a record array from a (flat) list of arrays

## this is not useful for generic purpose sudhanshu sir said  //// sudhanshu sir also said he never used...

In [105]:
x1 = np.array([1,2,3,4])

In [106]:
x2 = np.array(['a','dd','xyz','12'])

In [107]:
x3 = np.array([1.1,2,3,4])
x4 = np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [108]:
type(x2)

numpy.ndarray

In [109]:
r = np.core.records.fromarrays([x1,x2,x3,x4])
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('f0', '<i4'), ('f1', '<U3'), ('f2', '<f8'), ('f3', '<f8')])

In [110]:
r[1]

(2, 'dd', 2., 2.)

In [111]:
r[1]['f0']

2

In [112]:
r[1]['f1']

'dd'

In [113]:
r[0]

(1, 'a', 1.1, 1.1)

In [114]:
r[0][2]

1.1

In [115]:
r[1]["f1"]

'dd'

## Data types in NUMPY

In [116]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [117]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [118]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")

Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [119]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [120]:
list(range(1,4))

[1, 2, 3]

In [121]:
## range btayega

list(range(3,7))

[3, 4, 5, 6]

In [122]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [123]:
np.arange(1,6,1.1)

array([1. , 2.1, 3.2, 4.3, 5.4])

In [124]:
### for float dataset execution we will use arange() fxn ///// instead of range() fxn......

np.arange(2,17,2.3)

array([ 2. ,  4.3,  6.6,  8.9, 11.2, 13.5, 15.8])

In [125]:
np.arange(2.3,18,2)

array([ 2.3,  4.3,  6.3,  8.3, 10.3, 12.3, 14.3, 16.3])

In [126]:
np.arange(1.2,25.2,2)

array([ 1.2,  3.2,  5.2,  7.2,  9.2, 11.2, 13.2, 15.2, 17.2, 19.2, 21.2,
       23.2])

In [127]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [128]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [129]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


## Linspace()

In [130]:
np.linspace(2,5,14)

array([2.        , 2.23076923, 2.46153846, 2.69230769, 2.92307692,
       3.15384615, 3.38461538, 3.61538462, 3.84615385, 4.07692308,
       4.30769231, 4.53846154, 4.76923077, 5.        ])

In [131]:
np.linspace(1,6,20)

array([1.        , 1.26315789, 1.52631579, 1.78947368, 2.05263158,
       2.31578947, 2.57894737, 2.84210526, 3.10526316, 3.36842105,
       3.63157895, 3.89473684, 4.15789474, 4.42105263, 4.68421053,
       4.94736842, 5.21052632, 5.47368421, 5.73684211, 6.        ])

In [132]:
np.linspace(1,5,50)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [133]:
np.linspace(1,5,50, endpoint = True)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [134]:
np.linspace(1,5,50, endpoint = False)

array([1.  , 1.08, 1.16, 1.24, 1.32, 1.4 , 1.48, 1.56, 1.64, 1.72, 1.8 ,
       1.88, 1.96, 2.04, 2.12, 2.2 , 2.28, 2.36, 2.44, 2.52, 2.6 , 2.68,
       2.76, 2.84, 2.92, 3.  , 3.08, 3.16, 3.24, 3.32, 3.4 , 3.48, 3.56,
       3.64, 3.72, 3.8 , 3.88, 3.96, 4.04, 4.12, 4.2 , 4.28, 4.36, 4.44,
       4.52, 4.6 , 4.68, 4.76, 4.84, 4.92])

# Matrix creation

In [135]:
### in pytorch and in Tensorflow we will use MATRIX CREATION

### MATRIX CREATION IS VERY USEFUL WE WILL USE THIS IN MANY CLASSES


In [136]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [137]:
(np.zeros(6))

array([0., 0., 0., 0., 0., 0.])

In [138]:
## (3,4) is dimension
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [139]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [140]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [141]:
(np.ones(5))

array([1., 1., 1., 1., 1.])

In [142]:
np.ones((4,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [143]:
np.ones((3,4))+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [144]:
## 2nd way of representing the above

7+np.ones((3,4))

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [145]:
np.ones((3,4))+10

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [146]:
10+np.ones((3,4))

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [147]:
np.empty((3,4))

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [148]:
## it gave some random result and np.empty() nature is the same.

import numpy as np
np.empty((3,4))

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [149]:
##### np.eye() is identity matrix....diagonal element is 1 and other will be 0.....

mat1 = np.eye(4) 
mat1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [150]:
mat2 = np.eye(4,6)
mat2

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

## notice step difference is same in this below...

In [151]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [152]:
np.linspace(2.0, 3.0, num=5, endpoint=False)


array([2. , 2.2, 2.4, 2.6, 2.8])

In [153]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [154]:
#Return numbers spaced evenly on a log scale.
## notice step difference is same in this below...

np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [155]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [156]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [157]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

##### Assignment

In [158]:
import numpy as np
(np.zeros((3,4,8))+5)*2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [159]:
b = np.linspace(4,8,80)
b

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [160]:
a = ([[2,4,5],[5,6,7]])

In [161]:
a

[[2, 4, 5], [5, 6, 7]]

In [162]:
np.mat(a)

matrix([[2, 4, 5],
        [5, 6, 7]])

In [163]:
a =np.ones((4,5,2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [164]:
a.ndim

3

In [165]:
a.shape

(4, 5, 2)

In [166]:
a.dtype

dtype('float64')

In [167]:
x1 = ((1,2,3))
x2 = ((4,5,6))

In [168]:
x1+x2

(1, 2, 3, 4, 5, 6)

In [169]:
#Extract a diagonal or construct a diagonal array.

In [174]:
np.arange(16).reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [176]:
 np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [177]:
Y = np.arange(20).reshape(5,4)

In [178]:
np.diag(Y)

array([ 0,  5, 10, 15])

In [181]:
### 4 - dim
np.arange(16).reshape(8,2,1,1)

array([[[[ 0]],

        [[ 1]]],


       [[[ 2]],

        [[ 3]]],


       [[[ 4]],

        [[ 5]]],


       [[[ 6]],

        [[ 7]]],


       [[[ 8]],

        [[ 9]]],


       [[[10]],

        [[11]]],


       [[[12]],

        [[13]]],


       [[[14]],

        [[15]]]])

In [187]:
### (-1) is the default one (-1) will understand the condition by default........

np.arange(16).reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [191]:
b = np.arange(16).reshape(8,-1)

In [192]:
b

array([[  0,  -1],
       [ -2,  -3],
       [ -4,  -5],
       [ -6,  -7],
       [ -8,  -9],
       [-10, -11],
       [-12, -13],
       [-14, -15]])

In [193]:
np.diag(b)

array([ 0, -3])

In [200]:
J = np.arange(16).reshape(-1,4)

In [201]:
J

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [202]:
np.diag(J)

array([ 0,  5, 10, 15])

In [194]:
np.arange(16).reshape(-15156366,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [199]:
np.arange(16).reshape(-15156366,-45)

## ek hi -1 or unknown function legA AUR HONA CHAHIYE

ValueError: can only specify one unknown dimension

In [213]:
J

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [214]:
## not use k much in real life use

np.diag(J, k = 0)

array([ 0,  5, 10, 15])

In [205]:
np.diag(J, k = 1)

array([ 1,  6, 11])

In [206]:
np.diag(J, k = 2)

array([2, 7])

In [207]:
np.diag(J, k = 3)

array([3])

In [209]:
np.diag(J, k = -1)

array([ 4,  9, 14])

In [210]:
np.diag(J, k = -2)

array([ 8, 13])

In [211]:
np.diag(J, k = -3)

array([12])

In [212]:
np.diag(J, k = -4)

array([], dtype=int32)

In [215]:
np.diag(np.diag(J))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [216]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [217]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [220]:
np.diagflat([[1,2], [3,4]], k = 1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [221]:
np.diagflat([[1,2], [3,4]], k = 2)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [222]:
np.diagflat([[1,2], [3,4]], k = 3)

array([[0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [224]:
np.diagflat([[1,2], [3,4]], k = 4)

array([[0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [223]:
np.diagflat([[1,2], [3,4]], k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [227]:
np.diagflat([1,2], 1)



array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [228]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [229]:
np.tri(3, 3, 1, dtype=int)

array([[1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [230]:
np.tri(5, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [231]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [236]:
a = np.tri(5, 7, 1, dtype=int)
for i in a:
    for j in i:
        print(j)

1
1
0
0
0
0
0
1
1
1
0
0
0
0
1
1
1
1
0
0
0
1
1
1
1
1
0
0
1
1
1
1
1
1
0


In [237]:
#return a Lower triangle of an array.

In [239]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [240]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [241]:
#return Upper triangle of an array.

In [242]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [244]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [246]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [247]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

# Random number generation

In [248]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary

Random number generation (from Uniform distribution)
[[0.68175139 0.20225849 0.58038425]
 [0.00249957 0.92404603 0.27047749]]


In [251]:
np.random.rand(2,3)

array([[0.07778946, 0.7776689 , 0.2459382 ],
       [0.69634703, 0.78027953, 0.89270752]])

In [252]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.28460439  1.94891936  0.21306594]
 [-1.63639993 -0.39276325 -1.050976  ]
 [-0.21733407  0.16063252 -0.01946619]
 [-0.57039484  0.17316329 -0.70498771]]


In [254]:
np.random.randn(4,3)

array([[-1.05459574,  0.02998855,  0.02807355],
       [-0.58217972,  1.96245267, -0.07003142],
       [ 0.03447458, -0.46793352,  1.13066463],
       [ 0.73723131, -0.35382989, -0.35039582]])

In [255]:
np.random.randn(4,3,5)

array([[[ 1.82155593, -0.20627859,  0.79706564, -0.65323273,
          1.91768168],
        [-0.76289182,  2.44306426,  0.11221751, -0.12724004,
          1.52749534],
        [-0.22978718,  0.91789403,  0.67601053, -0.24920881,
          0.87120697]],

       [[-1.30718581, -1.56755394,  0.36180513,  0.92709643,
         -0.47231869],
        [ 2.05969265,  0.74386309, -1.25446247, -1.16895028,
         -0.98328285],
        [-0.22489904,  1.70942596, -0.78623301,  1.48304932,
         -0.99667681]],

       [[ 0.17434348,  1.04601361,  0.36676878,  1.13012883,
          0.04693927],
        [-0.46599007, -1.11205054,  1.57409914,  0.78551828,
          2.66994283],
        [-1.49821748, -0.15837473, -0.13935631, -0.56948097,
          1.82957178]],

       [[ 0.44369947, -1.61434377, -1.12875618, -0.82485175,
         -1.02414136],
        [ 0.22489064, -0.84844353,  0.56181826,  2.27832876,
         -0.94187949],
        [ 1.37969987, -0.05891237, -0.58168869,  0.15072283,
         

In [261]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")

Random integer vector: 4

Random integer matrix


In [259]:
np.random.randint(1,10)

2

In [265]:
np.random.randint(1,100,(4,4))

array([[73, 63, 85, 35],
       [82, 86, 71, 39],
       [ 2, 73, 55, 35],
       [77, 19, 88, 91]])

In [266]:
np.random.randint(1,100,(4,4,5))

array([[[33, 25, 26, 10,  5],
        [66, 93, 95, 72, 91],
        [ 5, 15,  1, 78, 44],
        [78, 17, 89, 64, 50]],

       [[60, 42, 72, 88, 47],
        [45, 42,  6, 12, 63],
        [24, 97, 19, 34, 93],
        [24, 38, 30,  1, 63]],

       [[58, 71, 79, 50, 55],
        [92, 90,  8, 89, 90],
        [ 8, 70, 57, 57, 14],
        [64, 93, 25, 33, 43]],

       [[50, 97, 18, 61, 22],
        [71,  2, 56, 55,  6],
        [41, 23,  7, 13, 47],
        [95, 65, 81, 59, 83]]])

In [268]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[49 13 13 14]
 [ 2 53 85 21]
 [84 29 38 31]
 [30 55 63 64]]

20 samples drawn from a dice throw: [1 6 3 5 2 6 6 5 6 6 4 2 6 5 5 2 4 2 1 6]


# Reshaping

In [270]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[35, 20, 71, 77, 42],
       [83, 85, 35,  7,  8],
       [13, 19, 83, 20, 85],
       [ 1,  9, 37, 16, 51],
       [51, 57, 21, 44, 24],
       [73, 60, 64, 55, 10]])

In [271]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [272]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


a looks like
 -------------------- 
 [35 20 71 77 42 83 85 35  7  8 13 19 83 20 85  1  9 37 16 51 51 57 21 44
 24 73 60 64 55 10] 
 --------------------

b looks like
 -------------------- 
 [[[35 20 71 77 42]
  [83 85 35  7  8]
  [13 19 83 20 85]]

 [[ 1  9 37 16 51]
  [51 57 21 44 24]
  [73 60 64 55 10]]] 
 --------------------

c looks like
 -------------------- 
 [[35 20 71 77 42]
 [83 85 35  7  8]
 [13 19 83 20 85]
 [ 1  9 37 16 51]
 [51 57 21 44 24]
 [73 60 64 55 10]] 
 --------------------


In [278]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [ 7 46  6 39 34 74 11 20 54 67]

Here is the sorted vector
 -------------------------------------------------- 
 [ 6  7 11 20 34 39 46 54 67 74]


In [276]:
# Vector of random interegrs

A = ri(1,100,10)
A

array([23, 75, 85, 61, 54, 49, 85, 50, 33, 78])

In [277]:
np.sort(A)

array([23, 33, 49, 50, 54, 61, 75, 78, 85, 85])

In [279]:
M = ri(1,100,25).reshape(5,5)

In [280]:
M

array([[53, 52,  1, 15, 46],
       [79, 82,  5, 17, 21],
       [10, 42, 89, 59, 39],
       [65, 22, 22, 38, 99],
       [17, 42, 35, 32, 62]])

In [282]:
### IDEA YE HOTA HAI (AXIS =1) HAI TOH COLUMN WISE SORT KAREGA BUT YAHAN IMPLEMENTATION DUSRA HAI YAHAN 
#(AXIS = 1) HAI TOH SORTING ROW WISE HOGA

np.sort(M, axis=1, kind='mergesort')

array([[ 1, 15, 46, 52, 53],
       [ 5, 17, 21, 79, 82],
       [10, 39, 42, 59, 89],
       [22, 22, 38, 65, 99],
       [17, 32, 35, 42, 62]])

In [283]:
### IDEA YE HOTA HAI (AXIS =0) HAI TOH ROW WISE SORT KAREGA BUT YAHAN IMPLEMENTATION DUSRA HAI YAHAN 
#(AXIS = 0) HAI TOH SORTING COLUMN WISE HOGA

np.sort(M, axis=0, kind='mergesort')

array([[10, 22,  1, 15, 21],
       [17, 42,  5, 17, 39],
       [53, 42, 22, 32, 46],
       [65, 52, 35, 38, 62],
       [79, 82, 89, 59, 99]])

In [284]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 99
Max of b: 85


array([[[35, 20, 71, 77, 42],
        [83, 85, 35,  7,  8],
        [13, 19, 83, 20, 85]],

       [[ 1,  9, 37, 16, 51],
        [51, 57, 21, 44, 24],
        [73, 60, 64, 55, 10]]])

In [285]:
M

array([[53, 52,  1, 15, 46],
       [79, 82,  5, 17, 21],
       [10, 42, 89, 59, 39],
       [65, 22, 22, 38, 99],
       [17, 42, 35, 32, 62]])

In [292]:
a

array([35, 20, 71, 77, 42, 83, 85, 35,  7,  8, 13, 19, 83, 20, 85,  1,  9,
       37, 16, 51, 51, 57, 21, 44, 24, 73, 60, 64, 55, 10])

In [289]:
b

array([[[35, 20, 71, 77, 42],
        [83, 85, 35,  7,  8],
        [13, 19, 83, 20, 85]],

       [[ 1,  9, 37, 16, 51],
        [51, 57, 21, 44, 24],
        [73, 60, 64, 55, 10]]])

In [290]:
c

array([[35, 20, 71, 77, 42],
       [83, 85, 35,  7,  8],
       [13, 19, 83, 20, 85],
       [ 1,  9, 37, 16, 51],
       [51, 57, 21, 44, 24],
       [73, 60, 64, 55, 10]])

In [287]:
print("Max of a location:", M.argmax() )
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: 19
Max of b location: 6
Max of c location: 6


In [291]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax(axis= 1))
print("Max of c location:", b.argmax(axis= 1))

Max of a location: [0 1 2 4 4]
Max of b location: [[1 1 2 0 2]
 [2 2 2 2 0]]
Max of c location: [[1 1 2 0 2]
 [2 2 2 2 0]]


# Indexing and slicing

In [293]:
arr = np.arange(0,11)
print("Array:",arr)

Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [294]:
print("Element at 7th index is:", arr[7])

Element at 7th index is: 7


In [295]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])

Elements from 3rd to 5th index are: [3 5]


In [296]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [297]:
print("Elements from last backwards are:", arr[-1:7:-1])

Elements from last backwards are: [10  9  8]


In [298]:
print("3 Elements from last backwards are:", arr[-1:-6:2])

3 Elements from last backwards are: []


In [299]:
arr = np.arange(0,21,2)
print("New array:",arr)

New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [300]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [305]:
import numpy as np 
mat = np.array(ri(10,100,45)).reshape(3,5,3)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[[12 76 16]
  [83 22 87]
  [33 38 62]
  [70 56 96]
  [86 60 59]]

 [[38 29 51]
  [54 65 38]
  [46 73 88]
  [13 47 45]
  [85 69 76]]

 [[80 92 27]
  [99 77 77]
  [13 37 61]
  [13 22 12]
  [19 33 47]]]


array([[[83, 22, 87],
        [70, 56, 96]],

       [[54, 65, 38],
        [13, 47, 45]],

       [[99, 77, 77],
        [13, 22, 12]]])

In [307]:
mat

array([[[12, 76, 16],
        [83, 22, 87],
        [33, 38, 62],
        [70, 56, 96],
        [86, 60, 59]],

       [[38, 29, 51],
        [54, 65, 38],
        [46, 73, 88],
        [13, 47, 45],
        [85, 69, 76]],

       [[80, 92, 27],
        [99, 77, 77],
        [13, 37, 61],
        [13, 22, 12],
        [19, 33, 47]]])

In [308]:
mat[0]

array([[12, 76, 16],
       [83, 22, 87],
       [33, 38, 62],
       [70, 56, 96],
       [86, 60, 59]])

In [309]:
mat[0][1]

array([83, 22, 87])

In [311]:
mat[1][:,1]

array([29, 65, 73, 47, 69])

In [316]:
mat[0:3,[0,1]]

array([[[12, 76, 16],
        [83, 22, 87]],

       [[38, 29, 51],
        [54, 65, 38]],

       [[80, 92, 27],
        [99, 77, 77]]])

# Subseting

In [319]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[83 93 26 44 33]
 [85 36 40 69 63]
 [22 75 84 54 84]]


array([[ True,  True, False, False, False],
       [ True, False, False,  True,  True],
       [False,  True,  True,  True,  True]])

In [320]:
mat = np.array(ri(10,100,15)).reshape(3,5)
mat>50

array([[False,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [False,  True,  True,  True,  True]])

In [321]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [81 71 56 72 79 81 55 96 74 93 82 63]


In [323]:
mat[mat>50]

array([81, 71, 56, 72, 79, 81, 55, 96, 74, 93, 82, 63])

# Slicing

### entire slicing pehle hi uppar kar chuke h sudh sir toh j.n.book se copy kiya h pura

In [324]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [326]:
mat_slice = mat[:2,:2]
mat_slice

array([[11, 12],
       [21, 22]])

In [327]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [328]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)


But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [329]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [330]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [331]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)


Change the sliced matrix
[[1000   12]
 [  21   22]]


In [332]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [333]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


1st Matrix of random single-digit numbers
----------------------------------------
 [[9 2 2]
 [3 8 3]
 [4 6 4]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[1 8 8]
 [2 9 5]
 [2 9 9]]


In [334]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)

In [339]:
print(mat1,"\n")
print(mat2 ,"\n")

[[3 1 5]
 [9 7 1]
 [9 6 7]] 

[[6 9 1]
 [9 7 8]
 [9 9 4]] 



In [343]:
## this is just a index wise multiplication
mat1*mat2

array([[18,  9,  5],
       [81, 49,  8],
       [81, 54, 28]])

In [342]:
##this is original matrix multiplication

mat1@mat2

array([[ 72,  79,  31],
       [126, 139,  69],
       [171, 186,  85]])

In [344]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


<ipython-input-344-ea15cab37cb9>:1: RuntimeWarning: divide by zero encountered in true_divide
  print("\nDivision\n------------------\n", mat1/0)


In [345]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[103 101 105]
 [109 107 101]
 [109 106 107]]


In [346]:
(100+mat1)

array([[103, 101, 105],
       [109, 107, 101],
       [109, 106, 107]])

In [347]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[ 27   1 125]
 [729 343   1]
 [729 216 343]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[ 27   1 125]
 [729 343   1]
 [729 216 343]]


In [349]:
(mat1**3)


array([[ 27,   1, 125],
       [729, 343,   1],
       [729, 216, 343]], dtype=int32)

In [350]:
(pow(mat1,3))

array([[ 27,   1, 125],
       [729, 343,   1],
       [729, 216, 343]], dtype=int32)

## Broadcasting

In [351]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [352]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [353]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [354]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [358]:
## 1ST WAY OF DOING
np.array([[0,1,2,3]]).T

array([[0],
       [1],
       [2],
       [3]])

In [359]:
## 2ND WAY OF DOING

# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [356]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [360]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math


In [361]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[7 2 7]
 [4 5 5]
 [9 2 1]]

2nd Matrix of random single-digit numbers
------------
 [[7 2 2]
 [5 8 4]
 [1 7 5]]


In [362]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


Sq-root of 1st matrix using np
------------------
 [[2.64575131 1.41421356 2.64575131]
 [2.         2.23606798 2.23606798]
 [3.         1.41421356 1.        ]]


In [363]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.09663316e+03 7.38905610e+00 1.09663316e+03]
 [5.45981500e+01 1.48413159e+02 1.48413159e+02]
 [8.10308393e+03 7.38905610e+00 2.71828183e+00]]


In [364]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.84509804 0.30103    0.84509804]
 [0.60205999 0.69897    0.69897   ]
 [0.95424251 0.30103    0.        ]]
[[7 2 7]
 [4 5 5]
 [9 2 1]]
[[7 2 2]
 [5 8 4]
 [1 7 5]]


In [365]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[0 0 1]
 [4 5 1]
 [0 2 1]]


array([[0, 0, 1],
       [4, 5, 1],
       [0, 2, 1]], dtype=int32)

In [366]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)


Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [367]:
A = np.linspace(0,12*np.pi,1001)

In [368]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])